/* FitStart — device-local fitness tracker. Storage is isolated behind Store for a future sync adapter. */
const DB_NAME = 'fitstart-device-db';
const DB_VERSION = 1;
const STORE_NAME = 'records';
const STATE_KEY = 'main';
const DAY_MS = 86400000;
const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const todayKey = (date=new Date()) => { const d = new Date(date.getTime()-date.getTimezoneOffset()*60000); return d.toISOString().slice(0,10); };
function upsertWeight(weight,date=todayKey()){const numeric=Number(weight);if(!(numeric>0))return;const index=state.weightHistory.findIndex(item=>item.date===date);if(index>=0)state.weightHistory[index].weight=numeric;else state.weightHistory.push({date,weight:numeric});}
const uid = () => crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(16).slice(2)}`;
const program = {
 A:[
  {id:'leg-press',name:'Leg Press',sets:2,reps:'10–12',rest:90,how:'Oyoq panjalari yelkadan sal keng. Tizzani qulflamang; qulay chuqurlikkacha sekin tushiring.'},
  {id:'chest-press',name:'Chest Press',sets:2,reps:'10–12',rest:90,how:'Tutqichlar ko‘krak o‘rtasida. Yelkalarni past tutib, og‘irlikni nazorat bilan itaring.'},
  {id:'lat-pulldown',name:'Lat Pulldown',sets:2,reps:'10–12',rest:90,how:'Barni ko‘krak yuqorisiga torting. Tanani orqaga qattiq tashlamang.'},
  {id:'seated-row',name:'Seated Row',sets:2,reps:'10–12',rest:75,how:'Belni tik tuting. Tirsaklarni orqaga olib, kuraklarni yengil yaqinlashtiring.'},
  {id:'leg-curl',name:'Leg Curl',sets:2,reps:'10–12',rest:75,how:'Harakatni sekin bajaring; tizzada og‘riq bo‘lsa diapazonni kichraytiring.'},
  {id:'shoulder-press',name:'Shoulder Press',sets:2,reps:'10',rest:75,how:'Yengil vazn tanlang. Belni bukmasdan, og‘riqsiz diapazonda itaring.'},
  {id:'plank',name:'Plank',sets:2,reps:'20–30 soniya',rest:60,how:'Tana bir chiziqda, qorin yengil tarang. Bel og‘risa darhol to‘xtating.'}
 ],
 B:[
  {id:'goblet-squat',name:'Goblet Squat (yengil)',sets:2,reps:'8–10',rest:90,how:'Avval vaznsiz sinang yoki juda yengil gantel ushlang. Tizzalar oyoq uchi tomonga qarasin.'},
  {id:'chest-press',name:'Chest Press',sets:2,reps:'10–12',rest:90,how:'Tutqichlar ko‘krak o‘rtasida. Yelkalarni past tutib, og‘irlikni nazorat bilan itaring.'},
  {id:'lat-pulldown',name:'Lat Pulldown',sets:2,reps:'10–12',rest:90,how:'Barni ko‘krak yuqorisiga torting. Tanani orqaga qattiq tashlamang.'},
  {id:'hip-thrust',name:'Glute Bridge',sets:2,reps:'10–12',rest:75,how:'Polga yotib, tovon bilan itaring. Belni haddan tashqari qayirmang.'},
  {id:'seated-row',name:'Seated Row',sets:2,reps:'10–12',rest:75,how:'Belni tik tuting. Tirsaklarni orqaga olib, kuraklarni yengil yaqinlashtiring.'},
  {id:'dead-bug',name:'Dead Bug',sets:2,reps:'Har tomonga 8',rest:60,how:'Belni polga yengil bosib, qarama-qarshi qo‘l va oyoqni sekin uzating.'},
  {id:'walk',name:'Yengil yurish',sets:1,reps:'10–15 daqiqa',rest:0,how:'Gaplasha oladigan darajadagi qulay tezlikni tanlang.'}
 ]
};
const freshState = () => ({version:1, onboarded:false, profile:{goal:'lose',currentWeight:'',startWeight:'',targetWeight:'',height:'',age:'',experience:'never',days:3,stepsGoal:7500,waterGoal:2.5,calorieGoal:2100,proteinGoal:140}, checkins:{}, sessions:{}, weightHistory:[], achievements:[], settings:{weekStartsMonday:true}});
let state = freshState();
let activeRoute = 'today';
let monthCursor = new Date(new Date().getFullYear(),new Date().getMonth(),1);
let currentWorkoutDay = 'A';
let toastTimer;

const Store = {
 db:null,
 async open(){
  if(!('indexedDB' in window)) return;
  this.db = await new Promise((resolve,reject)=>{
   const req=indexedDB.open(DB_NAME,DB_VERSION);
   req.onupgradeneeded=()=>{ if(!req.result.objectStoreNames.contains(STORE_NAME)) req.result.createObjectStore(STORE_NAME); };
   req.onsuccess=()=>resolve(req.result); req.onerror=()=>reject(req.error);
  });
  try { await navigator.storage?.persist?.(); } catch {}
 },
 async get(){ if(!this.db) return JSON.parse(localStorage.getItem('fitstart-backup-state')||'null'); return new Promise((resolve,reject)=>{const tx=this.db.transaction(STORE_NAME,'readonly');const req=tx.objectStore(STORE_NAME).get(STATE_KEY);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error);}); },
 async put(value){ if(!this.db){localStorage.setItem('fitstart-backup-state',JSON.stringify(value));return;} return new Promise((resolve,reject)=>{const tx=this.db.transaction(STORE_NAME,'readwrite');tx.objectStore(STORE_NAME).put(value,STATE_KEY);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);}); }
};
async function persist(){try{await Store.put(state);}catch(e){console.error(e);showToast('Saqlashda xatolik. JSON backup oling.');}}
function showToast(message){const region=$('#toast-region');const el=document.createElement('div');el.className='toast';el.textContent=message;region.append(el);setTimeout(()=>el.classList.add('show'),10);setTimeout(()=>{el.classList.remove('show');setTimeout(()=>el.remove(),250)},2600);}
function fmtDate(date=new Date(),opts={weekday:'long',day:'numeric',month:'long'}){return new Intl.DateTimeFormat('uz-UZ',opts).format(date);}
function weekNumber(date=new Date()){const start=new Date(state.profile.startDate||todayKey(date));return Math.max(1,Math.floor((new Date(todayKey(date))-new Date(todayKey(start)))/ (7*DAY_MS))+1);}
function trainingDay(dateKey=todayKey()){
 const date=new Date(`${dateKey}T12:00:00`); const start=new Date(`${state.profile.startDate||dateKey}T12:00:00`);const diff=Math.max(0,Math.floor((date-start)/DAY_MS));
 return {day:diff+1,week:Math.floor(diff/7)+1, weekday:date.getDay(), isTraining:[1,3,5].includes(date.getDay()), letter:(Math.floor(diff/7)%2===0?['A','B','A']:['B','A','B'])[[1,3,5].indexOf(date.getDay())]||'A'};
}
function todaySession(){return state.sessions[todayKey()]||null;}
function doneCount(session){return session?.exercises?.reduce((n,e)=>n+(e.done?1:0),0)||0;}
function ring(value,max,color='var(--lime)',size=104){let pct=max?Math.min(100,Math.max(0,value/max*100)):0;return `<div class="ring" style="--pct:${pct}%;--ring-color:${color};--ring-size:${size}px"><div><b>${Math.round(pct)}%</b></div></div>`;}
function sectionTitle(kicker,title,sub=''){return `<div class="section-heading"><div><span class="eyebrow">${kicker}</span><h2>${title}</h2>${sub?`<p>${sub}</p>`:''}</div></div>`;}
function safetyNote(){return `<div class="safety-note"><span>ⓘ</span><p>Yengil vazndan boshlang va takrorlarni to‘g‘ri texnika bilan bajaring. O‘tkir og‘riq, bosh aylanishi yoki ko‘krak og‘rig‘i sezilsa, to‘xtang.</p></div>`;}
function onboarding(){
 $('#main').innerHTML=`<div class="onboarding"><div class="onboard-orb"></div><div class="brand large"><span class="brand-mark">F</span><span>fit<span class="brand-accent">start</span></span></div><span class="eyebrow">SOG‘LOM O‘ZGARISH, OZ-OZDAN</span><h1>Har kuni ozgina.<br><span>Katta natija.</span></h1><p class="muted">Sizga mos yengil reja tuzamiz. Shoshilmaymiz — muntazamlik muhim.</p>
 <form id="onboarding-form" class="form-stack"><fieldset><legend>Asosiy maqsad</legend><div class="choice-grid"><label class="choice"><input type="radio" name="goal" value="lose" checked><span>⚖️ Vazn kamaytirish</span></label><label class="choice"><input type="radio" name="goal" value="fitness"><span>🌿 Sog‘lom bo‘lish</span></label><label class="choice"><input type="radio" name="goal" value="muscle"><span>💪 Mushak qurish</span></label></div></fieldset>
 <div class="form-grid"><label>Hozirgi vazn (kg)<input name="currentWeight" type="number" min="30" max="300" step="0.1" placeholder="92.4"></label><label>Maqsad vazn (kg)<input name="targetWeight" type="number" min="30" max="300" step="0.1" placeholder="80"></label><label>Bo‘y (cm)<input name="height" type="number" min="100" max="230" placeholder="175"></label><label>Yosh<input name="age" type="number" min="14" max="100" placeholder="22"></label></div>
 <label>Tajriba<select name="experience"><option value="never">Avval mashq qilmaganman</option><option value="beginner">Boshlovchiman</option><option value="intermediate">O‘rtacha tajriba</option></select></label><label>Haftasiga necha kun?<select name="days"><option value="3">3 kun — tavsiya qilinadi</option><option value="2">2 kun</option><option value="4">4 kun</option></select></label><button class="primary-button full" type="submit">Mening rejamni boshlash <span>→</span></button></form><p class="tiny muted">Tibbiy tashxis yoki davolash ilovasi emas.</p></div>`;
 $('#onboarding-form').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.profile={...state.profile,goal:f.get('goal'),currentWeight:f.get('currentWeight'),startWeight:f.get('currentWeight'),targetWeight:f.get('targetWeight'),height:f.get('height'),age:f.get('age'),experience:f.get('experience'),days:Number(f.get('days')),startDate:todayKey()};upsertWeight(f.get('currentWeight'));state.onboarded=true;await persist();route('today');});
}
function renderToday(){
 const key=todayKey(), ci=state.checkins[key]||{}, training=trainingDay(key), session=todaySession(), isTraining=training.isTraining;
 const title=isTraining?`Mashg‘ulot ${training.letter}`:'Dam olish kuni';const workoutName=isTraining?`Full Body ${training.letter}`:'Yengil yurish va tiklanish';
 const steps=Number(ci.steps||0), water=Number(ci.water||0), stepGoal=Number(state.profile.stepsGoal||7500), waterGoal=Number(state.profile.waterGoal||2.5);
 const workoutDone=session?.completed||false;
 $('#main').innerHTML=`<section class="hero-card"><div class="hero-glow"></div><div class="hero-top"><span class="eyebrow">${escapeHTML(fmtDate())}</span><span class="status-chip ${isTraining?'':'rest'}">${isTraining?'● MASHQ KUNI':'○ TIKLANISH'}</span></div><div class="day-line"><div><h1>Salom${state.profile.name?`, ${escapeHTML(state.profile.name)}`:''} 👋</h1><p>DAY ${training.day} <span class="dot">·</span> WEEK ${training.week}</p></div><div class="streak-badge"><span class="flame">🔥</span><strong>${calcStreak()}</strong><small>kun</small></div></div><div class="hero-workout"><div><span class="eyebrow">BUGUNGI REJA</span><h2>${workoutName}</h2><p>${isTraining?'7 mashq · taxminan 40–50 daqiqa':'Yengil harakat va odatlar'}</p></div><span class="hero-icon">${isTraining?'◉':'☼'}</span></div><button class="primary-button" data-action="${isTraining?'start-workout':'walk'}">${workoutDone?'Mashq bajarildi ✓':isTraining?'Mashqni boshlash':'Yurishni qayd etish'} <span>→</span></button></section>
 <div class="metric-grid"><article class="metric-card"><div class="metric-head"><span>QADAMLAR</span><span>👟</span></div><div class="metric-row">${ring(steps,stepGoal,'var(--mint)',82)}<div><strong>${steps.toLocaleString('uz-UZ')}</strong><small>/ ${stepGoal.toLocaleString('uz-UZ')}</small></div></div><button class="text-button" data-action="edit-steps">+ Qadam qo‘shish</button></article><article class="metric-card"><div class="metric-head"><span> SUV</span><span>💧</span></div><div class="metric-row">${ring(water,waterGoal,'#73c8ff',82)}<div><strong>${water.toFixed(1)}</strong><small>/ ${waterGoal.toFixed(1)} L</small></div></div><button class="text-button" data-action="add-water">+ 250 ml qo‘shish</button></article></div>
 <section class="panel"><div class="panel-title"><div><span class="eyebrow">BUGUNGI CHECK-IN</span><h3>O‘zingizni qanday his qilyapsiz?</h3></div><button class="arrow-button" data-route="settings">→</button></div><div class="mood-row">${['😞','😐','🙂','😄','🔥'].map((m,i)=>`<button class="mood ${ci.mood===i?'selected':''}" data-action="mood" data-value="${i}" aria-label="Kayfiyat ${i+1}">${m}</button>`).join('')}</div><div class="checkin-row"><label class="mini-input">Vazn <input data-checkin="weight" value="${escapeHTML(ci.weight??state.profile.currentWeight)}" inputmode="decimal" placeholder="kg"></label><label class="mini-input">Uyqu <input data-checkin="sleep" value="${escapeHTML(ci.sleep||'')}" inputmode="decimal" placeholder="soat"></label><button class="save-mini" data-action="save-checkin">Saqlash</button></div></section>
 <section class="panel nutrition-card"><div class="panel-title"><div><span class="eyebrow">OVQATLANISH · IXTIYORIY</span><h3>Oddiy kuzatuv</h3></div><span>🥗</span></div>${[['calories','Kaloriya',ci.calories||0,state.profile.calorieGoal||0,'kcal'],['protein','Protein',ci.protein||0,state.profile.proteinGoal||0,'g']].map(([field,label,value,goal,unit])=>`<div class="nutrition-line"><div><span>${label}</span><b>${Number(value).toLocaleString()} <small>/ ${Number(goal).toLocaleString()} ${unit}</small></b></div><div class="quick-adjust"><button data-action="adjust-nutrition" data-field="${field}" data-delta="-1" aria-label="${label} kamaytir">−</button><button data-action="adjust-nutrition" data-field="${field}" data-delta="1" aria-label="${label} qo‘sh">+</button></div></div><div class="progress-track slim"><i style="width:${goal?Math.min(100,Number(value)/goal*100):0}%"></i></div>`).join('')}<p class="subtle">Kaloriya maqsadi shaxsiy ehtiyojdan farq qiladi. O‘zingizga mos maqsadni tanlang.</p></section>
 <section class="panel weekly-panel"><div class="panel-title"><div><span class="eyebrow">HAFTALIK MAQSAD</span><h3>Ritmingizni saqlang</h3></div><span class="weekly-count">${weeklyWorkouts()}/3</span></div><div class="week-dots">${[1,2,3,4,5,6,0].map((wd,i)=>{let d=new Date();d.setDate(d.getDate()-((d.getDay()-wd+7)%7));const k=todayKey(d), done=!!state.sessions[k]?.completed;return `<div class="week-dot ${done?'done':''} ${k===key?'today':''}"><span>${['Du','Se','Ch','Pa','Ju','Sh','Ya'][i]}</span><i>${done?'✓':d.getDate()}</i></div>`}).join('')}</div><div class="progress-track"><i style="width:${Math.min(100,weeklyWorkouts()/3*100)}%"></i></div><p class="subtle">${weeklyWorkouts()} ta mashg‘ulot bajarildi · maqsad 3 ta</p></section>
 ${safetyNote()}`;
}
function ensureSession(day='A',key=todayKey()){
 if(!state.sessions[key])state.sessions[key]={date:key,letter:day,exercises:program[day].map(x=>({id:x.id,name:x.name,sets:Array.from({length:x.sets},()=>({done:false,weight:''}))})),cardio:0,notes:'',completed:false};
 return state.sessions[key];
}
function renderWorkout(){
 const key=todayKey(), training=trainingDay(key), day=currentWorkoutDay||(training.isTraining?training.letter:'A');
 const s=state.sessions[key]; const exercises=program[day];
 $('#main').innerHTML=`${sectionTitle('BEGINNER MODE · 4 HAFTA','Mashg‘ulot','Haftasiga 3 marta. Har set orasida 60–90 soniya dam oling.')}
 <div class="week-banner"><span class="week-icon">🌱</span><div><strong>${training.week<=4?`1–4-HAFTA · ${['Moslashish','Texnikani o‘rganish','Yumshoq progress','Barqaror odat'][training.week-1]}`:'BARQAROR REJA'}</strong><p>Shoshilmasdan, qulay og‘irlikda boshlang.</p></div></div>
 <div class="segmented"><button data-action="choose-day" data-value="A" class="${day==='A'?'active':''}">DAY A</button><button data-action="choose-day" data-value="B" class="${day==='B'?'active':''}">DAY B</button><span class="rest-hint">Keyingi hafta A/B almashadi</span></div>
 <section class="workout-intro"><div><span class="eyebrow">FULL BODY ${day}</span><h2>${day==='A'?'Asosiy harakatlar':'Kuch va muvozanat'}</h2><p>Avval 5–10 daqiqa yo‘lakda yengil yuring.</p></div><div class="workout-progress">${ring(s?doneCount(s):0,exercises.length,'var(--lime)',75)}<small>${s?doneCount(s):0}/${exercises.length}</small></div></section>
 <div class="exercise-list">${exercises.map((ex,i)=>{const prev=latestExercise(ex.id);const session=(s?.letter===day?s:null);const saved=session?.exercises.find(e=>e.id===ex.id);return `<article class="exercise-card ${saved?.done?'completed':''}"><div class="exercise-heading"><div class="exercise-number">${saved?.done?'✓':String(i+1).padStart(2,'0')}</div><div class="exercise-title"><h3>${ex.name}</h3><p>${ex.sets} set × ${ex.reps} <span>·</span> dam ${ex.rest?`${ex.rest} s`:'—'}</p></div><button class="help-button" data-action="exercise-help" data-value="${ex.id}" aria-label="Ko‘rsatma">i</button></div><p class="exercise-how">${ex.how}</p><div class="sets-head"><span>SETLAR</span><span>OG‘IRLIK</span><span>BAJARILDI</span></div>${Array.from({length:ex.sets},(_,n)=>{const set=saved?.sets?.[n]||{done:false,weight:''};return `<div class="set-row"><span>Set ${n+1}</span><input class="weight-input" type="number" min="0" step="0.5" placeholder="kg" value="${escapeHTML(set.weight)}" data-weight="${ex.id}" data-set="${n}" aria-label="${ex.name}, set ${n+1}, vazn kilogramm"><button class="set-check ${set.done?'checked':''}" data-action="toggle-set" data-exercise="${ex.id}" data-set="${n}" aria-label="Set ${n+1} ${set.done?'bajarildi':'bajarildi deb belgilash'}">${set.done?'✓':'○'}</button></div>`}).join('')}${prev?.goodCount>=2?`<div class="recommendation">🌱 Oxirgi ${prev.goodCount} mashg‘ulotda setlar bajarildi. Keyingi safar texnika qulay bo‘lsa, ${prev.weight?`${prev.weight+1.25} kg`:'eng kichik vazn qadami'}ni sinab ko‘rishingiz mumkin. Majburiy emas.</div>`:prev?`<div class="recommendation">↗ O‘tgan safar: <b>${prev.weight||'vazn kiritilmagan'} kg</b>. Avval texnikani qulay his qilishga e’tibor bering.</div>`:''}</article>`}).join('')}</div>
 <div class="finish-card cardio-finish"><div class="cardio-heading"><span class="eyebrow">YAKUNLASH · YENGIL KARDIO</span><h3>10–15 daqiqa, qulay tezlik</h3><p>Gaplasha oladigan tezlikni saqlang.</p></div><div class="cardio-fields"><label class="cardio-input">Turi<select data-session="cardioType"><option>Walking</option><option>Treadmill</option><option>Cycling</option><option>Elliptical</option></select></label><label class="cardio-input">Vaqt <input data-session="cardio" type="number" min="0" placeholder="10" value="${escapeHTML(s?.cardio||'')}"></label><label class="cardio-input">Zo‘riqish<select data-session="intensity"><option>Easy</option><option selected>Moderate</option><option>Hard</option></select></label></div></div>
 <button class="primary-button full" data-action="finish-workout">Mashg‘ulotni saqlash <span>✓</span></button>${safetyNote()}`;
}
function latestExercise(id){let records=[];for(const ses of Object.values(state.sessions)){const ex=ses.exercises?.find(e=>e.id===id);if(ex?.sets?.length)records.push({date:ses.date,weight:Number(ex.sets.at(-1).weight||0),sets:ex.sets,good:ex.sets.every(s=>s.done)});}records.sort((a,b)=>a.date.localeCompare(b.date));const latest=records.at(-1);let goodCount=0;for(const record of records.slice(-3).reverse()){if(!record.good)break;goodCount++;}return latest?{...latest,goodCount}:null;}
function renderCalendar(){const year=monthCursor.getFullYear(), month=monthCursor.getMonth(), first=new Date(year,month,1), offset=(first.getDay()+6)%7, days=new Date(year,month+1,0).getDate(), keys=['Du','Se','Ch','Pa','Ju','Sh','Ya'];let cells='';for(let i=0;i<offset;i++)cells+='<span class="calendar-empty"></span>';for(let n=1;n<=days;n++){const key=todayKey(new Date(year,month,n));const ses=state.sessions[key];let cls=ses?.completed?'green':ses&&doneCount(ses)>0?'yellow':key<todayKey()&&trainingDay(key).isTraining?'red':'';cells+=`<button class="calendar-day ${cls} ${key===todayKey()?'is-today':''}" data-action="day-detail" data-value="${key}">${n}${cls?'<i></i>':''}</button>`;}
 $('#main').innerHTML=`${sectionTitle('FAOLLIGINGIZ','Kalendar','Har kuni kichik qadam ham hisobga olinadi.')}<section class="panel calendar-panel"><div class="calendar-head"><button data-action="month-prev" class="arrow-button">‹</button><h3>${new Intl.DateTimeFormat('uz-UZ',{month:'long',year:'numeric'}).format(monthCursor)}</h3><button data-action="month-next" class="arrow-button">›</button></div><div class="calendar-grid weekday-grid">${keys.map(x=>`<span>${x}</span>`).join('')}</div><div class="calendar-grid">${cells}</div><div class="legend"><span><i class="green"></i>Bajarildi</span><span><i class="yellow"></i>Qisman</span><span><i></i>Dam olish</span><span><i class="red"></i>O‘tkazib yuborildi</span></div></section><div class="panel-title calendar-summary"><div><span class="eyebrow">BU HAFTA</span><h3>${weeklyWorkouts()} / 3 mashg‘ulot</h3></div><span class="large-emoji">🌿</span></div><div class="panel"><h3>Haftalik sharh</h3><p class="subtle">${weeklyReview()}</p><button class="text-button" data-action="weekly-review">Sharhni ko‘rish →</button></div>`;
}
function dayDetail(key){const ci=state.checkins[key]||{}, ses=state.sessions[key],ex=ses?.exercises||[];openModal(`<div class="modal-top"><div><span class="eyebrow">KUNLIK TARIX</span><h2>${fmtDate(new Date(`${key}T12:00:00`),{weekday:'long',day:'numeric',month:'long'})}</h2></div><button class="close-modal" data-action="close-modal">×</button></div><div class="detail-stats"><div><b>${ci.weight||'—'} kg</b><small>Vazn</small></div><div><b>${Number(ci.steps||0).toLocaleString()}</b><small>Qadam</small></div><div><b>${Number(ci.water||0).toFixed(1)} L</b><small>Suv</small></div></div><h3>${ses?.completed?'Mashg‘ulot bajarildi ✓':ses?'Qisman mashq':'Mashg‘ulot yo‘q'}</h3><div class="detail-list">${ex.map(e=>`<p>${e.done?'✅':'◯'} ${escapeHTML(e.name)} <small>${e.sets.filter(s=>s.done).length}/${e.sets.length} set</small></p>`).join('')||'<p class="subtle">Mashq qayd qilinmagan.</p>'}</div><p class="subtle">Cardio: ${ses?.cardio||0} daqiqa · Uyqu: ${ci.sleep||'—'} soat</p>${ci.notes?`<p>${escapeHTML(ci.notes)}</p>`:''}`);}
function renderProgress(){const weights=state.weightHistory.filter(x=>Number(x.weight)>0).slice().sort((a,b)=>a.date.localeCompare(b.date));const current=Number(state.profile.currentWeight||weights.at(-1)?.weight||0),start=Number(state.profile.startWeight||weights[0]?.weight||0),goal=Number(state.profile.targetWeight||0),lost=start-current,remaining=current-goal;const avg=stepsAverage(7);const pct=start&&goal&&start!==goal?Math.max(0,Math.min(100,(start-current)/(start-goal)*100)):0;
 $('#main').innerHTML=`${sectionTitle('SIZNING SAFARINGIZ','Progress','Kundalik raqam emas, bir necha haftalik yo‘nalishga qaraymiz.')}<section class="weight-hero"><div><span class="eyebrow">HOZIRGI VAZN</span><div class="weight-number">${current?current.toFixed(1):'—'}<small>kg</small></div><p>${current&&start?`${lost>=0?lost.toFixed(1)+' kg kamaydi':'vazn oshdi'} · maqsadgacha ${Math.max(0,remaining).toFixed(1)} kg`: 'Boshlash uchun vazn kiriting'}</p></div><div class="goal-ring">${ring(pct,100,'var(--lime)',90)}<small>maqsad</small></div></section><div class="chart-panel panel"><div class="panel-title"><div><span class="eyebrow">VAZN TRENDI</span><h3>Oxirgi 30 kun</h3></div><span class="trend-pill">${trendLabel(weights)}</span></div>${weightChart(weights)}</div><div class="metric-grid three"><div class="stat-card"><span>MASHQLAR</span><b>${Object.values(state.sessions).filter(s=>s.completed).length}</b><small>jami</small></div><div class="stat-card"><span>STREAK</span><b>🔥 ${calcStreak()}</b><small>kun</small></div><div class="stat-card"><span>QADAM O‘RT.</span><b>${avg.toLocaleString()}</b><small>7 kun</small></div></div><div class="panel progress-summary"><div class="panel-title"><div><span class="eyebrow">ODATLAR</span><h3>So‘nggi 7 kun o‘rtachasi</h3></div></div><div class="habit-row"><span>💧 Suv</span><b>${waterAverage(7).toFixed(1)} L / kun</b></div><div class="habit-row"><span>👟 Qadam</span><b>${avg.toLocaleString()} / kun</b></div><div class="habit-row"><span>🏋️ Mashq bajarilishi</span><b>${workoutRate()}%</b></div></div><div class="panel"><span class="eyebrow">MILESTONE</span><h3>Davomiylik — eng katta yutuq 🌱</h3><p class="subtle">Vazn bir hafta o‘zgarmasa ham bu odatiy. 7 kunlik o‘rtacha va bir necha haftalik trendga qarang.</p></div>`;
}
function weightChart(items){if(items.length<2)return `<div class="empty-chart"><span>↗</span><p>Trend chizig‘i uchun kamida 2 ta vazn yozuvi kerak.</p><button class="text-button" data-action="add-weight">+ Vazn yozish</button></div>`;const cut=items.slice(-30), vals=cut.map(i=>Number(i.weight)),min=Math.min(...vals)-1,max=Math.max(...vals)+1,pts=vals.map((v,i)=>`${(i/(vals.length-1))*100},${90-((v-min)/(max-min||1))*72}`).join(' ');return `<svg class="weight-chart" viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Vazn o‘zgarishi grafigi"><defs><linearGradient id="chartFill" x1="0" x2="0" y1="0" y2="1"><stop stop-color="#a3f46b" stop-opacity=".32"/><stop offset="1" stop-color="#a3f46b" stop-opacity="0"/></linearGradient></defs><path d="M0 90 L${pts.split(' ').map(p=>p.replace(',',' ')).join(' L')} L100 100 L0 100Z" fill="url(#chartFill)"/><polyline points="${pts}" fill="none" stroke="#a3f46b" stroke-width="1.4" vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round"/>${pts.split(' ').map(p=>{let [x,y]=p.split(',');return `<circle cx="${x}" cy="${y}" r="1.2" fill="#a3f46b"/>`}).join('')}</svg><div class="chart-labels"><span>${cut[0].date.slice(5)}</span><span>${cut.at(-1).date.slice(5)}</span></div><p class="chart-average">7 kunlik o‘rtacha: <b>${rollingAverage(cut).toFixed(1)} kg</b></p>`;}
function rollingAverage(items){const subset=items.slice(-7);return subset.length?subset.reduce((s,x)=>s+Number(x.weight),0)/subset.length:0;}
function trendLabel(items){if(items.length<2)return 'Yangi boshlanish';const avgNow=rollingAverage(items.slice(-7)),avgPrev=rollingAverage(items.slice(-14,-7));return avgPrev?`${avgNow<avgPrev?'↓':avgNow>avgPrev?'↑':'→'} trend`: 'Kuzatilyapti';}
function renderSettings(){const p=state.profile;$('#main').innerHTML=`${sectionTitle('SIZGA MOSLAB','Profil va sozlamalar','Progress telefoningizda, shu qurilma ichida saqlanadi.')}
 <section class="panel settings-form"><div class="panel-title"><div><span class="eyebrow">PROFIL</span><h3>Asosiy ma’lumotlar</h3></div><span>☺</span></div><div class="form-grid"><label>Ism<input data-profile="name" value="${escapeHTML(p.name||'')}" placeholder="Ismingiz"></label><label>Yosh<input data-profile="age" type="number" value="${escapeHTML(p.age||'')}" placeholder="yosh"></label><label>Bo‘y (cm)<input data-profile="height" type="number" value="${escapeHTML(p.height||'')}" placeholder="cm"></label><label>Hozirgi vazn (kg)<input data-profile="currentWeight" type="number" step="0.1" value="${escapeHTML(p.currentWeight||'')}" placeholder="kg"></label><label>Boshlang‘ich vazn<input data-profile="startWeight" type="number" step="0.1" value="${escapeHTML(p.startWeight||'')}" placeholder="kg"></label><label>Maqsad vazn<input data-profile="targetWeight" type="number" step="0.1" value="${escapeHTML(p.targetWeight||'')}" placeholder="kg"></label></div><button class="primary-button full" data-action="save-profile">Profilni saqlash <span>✓</span></button></section>
 <section class="panel settings-form"><div class="panel-title"><div><span class="eyebrow">KUNLIK MAQSADLAR</span><h3>O‘zingizga moslang</h3></div><span>◉</span></div><div class="form-grid"><label>Qadam maqsadi<input data-profile="stepsGoal" type="number" value="${escapeHTML(p.stepsGoal)}"></label><label>Suv maqsadi (L)<input data-profile="waterGoal" type="number" step="0.1" value="${escapeHTML(p.waterGoal)}"></label><label>Kaloriya maqsadi<input data-profile="calorieGoal" type="number" value="${escapeHTML(p.calorieGoal)}"></label><label>Protein maqsadi (g)<input data-profile="proteinGoal" type="number" value="${escapeHTML(p.proteinGoal)}"></label></div><button class="primary-button full" data-action="save-profile">Maqsadlarni saqlash <span>✓</span></button></section>
 <section class="panel settings-form"><div class="panel-title"><div><span class="eyebrow">KUNLIK QAYD</span><h3>Bugungi check-in</h3></div></div><div class="form-grid"><label>Qadam<input data-checkin="steps" type="number" value="${escapeHTML(state.checkins[todayKey()]?.steps||'')}" placeholder="7500"></label><label>Suv (L)<input data-checkin="water" type="number" step="0.1" value="${escapeHTML(state.checkins[todayKey()]?.water||'')}" placeholder="2.5"></label><label>Kaloriya<input data-checkin="calories" type="number" value="${escapeHTML(state.checkins[todayKey()]?.calories||'')}" placeholder="2100"></label><label>Protein (g)<input data-checkin="protein" type="number" value="${escapeHTML(state.checkins[todayKey()]?.protein||'')}" placeholder="140"></label><label>Uyqu (soat)<input data-checkin="sleep" type="number" step="0.1" value="${escapeHTML(state.checkins[todayKey()]?.sleep||'')}" placeholder="7.5"></label></div><label class="full-label">Izoh<textarea data-checkin="notes" rows="3" placeholder="Bugungi qayd...">${escapeHTML(state.checkins[todayKey()]?.notes||'')}</textarea></label><button class="primary-button full" data-action="save-all-checkin">Check-in saqlash <span>✓</span></button></section>
 <section class="panel backup-panel"><span class="eyebrow">QURILMA BAZASI</span><h3>Ma’lumotlar shu telefonda saqlanadi</h3><p class="subtle">FitStart serverga yubormaydi. Safari sayt ma’lumotlarini o‘chirsangiz, baza ham o‘chishi mumkin — backup’ni vaqti-vaqti bilan yuklab oling.</p><div class="button-row"><button class="secondary-button" data-action="export">JSON export ↓</button><button class="secondary-button" data-action="import">JSON import ↑</button><input id="import-file" type="file" accept="application/json,.json" hidden></div></section>
 <section class="panel safety-panel"><span class="eyebrow">XAVFSIZLIK</span><h3>Tanangizga quloq soling</h3><p>Bu ilova tibbiy tashxis yoki davolash vositasi emas. Maksimal og‘irlik sinamang. O‘tkir og‘riq, bosh aylanishi, ko‘krak og‘rig‘i yoki noodatiy nafas qisishida mashqni to‘xtating.</p></section><button class="danger-button" data-action="reset">Ilova ma’lumotlarini yangidan boshlash</button>`;}
function route(name){activeRoute=name;location.hash=name;$$('.bottom-nav a').forEach(a=>a.classList.toggle('active',a.dataset.route===name));const map={today:renderToday,workout:renderWorkout,calendar:renderCalendar,progress:renderProgress,settings:renderSettings};(map[name]||renderToday)();$('#main').focus({preventScroll:true});}
function calcStreak(){let n=0,d=new Date();for(let i=0;i<400;i++){const k=todayKey(d);if(state.sessions[k]?.completed||state.checkins[k]?.steps>=state.profile.stepsGoal){n++;d.setDate(d.getDate()-1);}else if(i===0){d.setDate(d.getDate()-1);continue;}else break;}return n;}
function weeklyWorkouts(){const now=new Date(),monday=new Date(now);monday.setDate(now.getDate()-((now.getDay()+6)%7));let n=0;for(let i=0;i<7;i++){const d=new Date(monday);d.setDate(monday.getDate()+i);if(state.sessions[todayKey(d)]?.completed)n++;}return n;}
function workoutRate(){const eligible=Object.values(state.sessions).length;return eligible?Math.round(Object.values(state.sessions).filter(s=>s.completed).length/eligible*100):0;}
function stepsAverage(days){let n=0,total=0;for(let i=0;i<days;i++){const d=new Date();d.setDate(d.getDate()-i);const v=Number(state.checkins[todayKey(d)]?.steps||0);if(v){n++;total+=v;}}return n?Math.round(total/n):0;}
function waterAverage(days){let n=0,total=0;for(let i=0;i<days;i++){const d=new Date();d.setDate(d.getDate()-i);const v=Number(state.checkins[todayKey(d)]?.water||0);if(v){n++;total+=v;}}return n?total/n:0;}
function weeklyReview(){const sessions=weeklyWorkouts(),steps=stepsAverage(7);if(sessions>=3)return 'Ajoyib muntazamlik! Shu qulay ritmni saqlang.';if(sessions===0)return 'Bu hafta yengil yurishdan boshlang. Keyingi haftaga 2–3 ta mashg‘ulot rejalashtiring.';return `Bu hafta ${sessions}/3 mashg‘ulot bajardingiz. Keyingi haftada bir mashg‘ulot qo‘shishni maqsad qiling. ${steps?`O‘rtacha ${steps.toLocaleString()} qadam/kun.`:''}`;}
function openModal(html){const m=$('#modal');m.innerHTML=html;m.showModal();}
function saveCheckinInputs(){const key=todayKey();state.checkins[key]??={};$$('[data-checkin]').forEach(el=>state.checkins[key][el.dataset.checkin]=el.value);}
async function celebrate(message){showToast(message);const card=document.createElement('div');card.className='confetti';card.innerHTML=Array.from({length:24},(_,i)=>`<i style="--i:${i};--h:${(i*51)%360}deg"></i>`).join('');document.body.append(card);setTimeout(()=>card.remove(),1200);}
async function handleAction(btn){const action=btn.dataset.action,key=todayKey();switch(action){
 case 'start-workout':currentWorkoutDay=trainingDay().letter;route('workout');break;
 case 'walk':openModal(`<div class="modal-top"><div><span class="eyebrow">YENGIL HARAKAT</span><h2>Yurishni qayd etish</h2></div><button class="close-modal" data-action="close-modal">×</button></div><p class="subtle">O‘zingizga qulay tezlikda yuring. Gaplashish oson bo‘lishi kerak.</p><label class="field-label">Daqiqa<input id="walk-minutes" type="number" min="1" value="15"></label><button class="primary-button full" data-action="save-walk">Saqlash ✓</button>`);break;
 case 'save-walk':{const mins=Number($('#walk-minutes').value||0);state.sessions[key]??={date:key,letter:'REST',exercises:[],cardio:0,completed:false};state.sessions[key].cardio+=mins;await persist();$('#modal').close();route('today');showToast(`${mins} daqiqa yurish saqlandi`);break;}
 case 'edit-steps':openModal(`<div class="modal-top"><div><span class="eyebrow">QADAM</span><h2>Bugungi qadam</h2></div><button class="close-modal" data-action="close-modal">×</button></div><label class="field-label">Jami qadam<input id="steps-entry" type="number" min="0" value="${state.checkins[key]?.steps||''}" placeholder="masalan, 6200"></label><button class="primary-button full" data-action="save-steps">Saqlash ✓</button>`);break;
 case 'save-steps':state.checkins[key]??={};state.checkins[key].steps=Number($('#steps-entry').value||0);await persist();$('#modal').close();route('today');break;
 case 'add-water':state.checkins[key]??={};state.checkins[key].water=Math.round((Number(state.checkins[key].water||0)+0.25)*100)/100;await persist();route('today');showToast('250 ml suv qo‘shildi 💧');break;
 case 'adjust-nutrition':{const field=btn.dataset.field,step=field==='calories'?100:10;state.checkins[key]??={};state.checkins[key][field]=Math.max(0,Number(state.checkins[key][field]||0)+Number(btn.dataset.delta)*step);await persist();route('today');break;}
 case 'mood':state.checkins[key]??={};state.checkins[key].mood=Number(btn.dataset.value);await persist();route('today');break;
 case 'save-checkin':saveCheckinInputs();if(state.checkins[key].weight){state.profile.currentWeight=state.checkins[key].weight;upsertWeight(state.checkins[key].weight);}await persist();route('today');showToast('Check-in saqlandi');break;
 case 'save-all-checkin':saveCheckinInputs();await persist();route('settings');showToast('Check-in saqlandi');break;
 case 'choose-day':currentWorkoutDay=btn.dataset.value;renderWorkout();break;
 case 'toggle-set':{const letter=currentWorkoutDay||'A',ses=ensureSession(letter);const ex=ses.exercises.find(x=>x.id===btn.dataset.exercise);ex.sets[Number(btn.dataset.set)].done=!ex.sets[Number(btn.dataset.set)].done;ses.completed=ses.exercises.length>0&&ses.exercises.every(e=>e.sets.every(s=>s.done));await persist();renderWorkout();if(ses.completed)celebrate('Mashg‘ulot bajarildi! Zo‘r ish 🎉');break;}
 case 'finish-workout':{const ses=ensureSession(currentWorkoutDay||'A');$$('[data-weight]').forEach(el=>{const ex=ses.exercises.find(x=>x.id===el.dataset.weight);if(ex)ex.sets[Number(el.dataset.set)].weight=el.value;});ses.cardio=Number($('[data-session="cardio"]')?.value||0);ses.cardioType=$('[data-session="cardioType"]')?.value||'Walking';ses.intensity=$('[data-session="intensity"]')?.value||'Moderate';ses.completed=ses.exercises.every(e=>e.sets.every(s=>s.done));ses.finishedAt=new Date().toISOString();if(ses.completed)state.achievements=Array.from(new Set([...state.achievements,'first-workout',...(Object.values(state.sessions).filter(s=>s.completed).length>=10?['ten-workouts']:[])]));await persist();route('today');showToast(ses.completed?'Mashg‘ulot to‘liq saqlandi!':'Mashq qisman saqlandi — yaxshi boshlanish.');break;}
 case 'exercise-help':{const ex=Object.values(program).flat().find(e=>e.id===btn.dataset.value);if(ex)openModal(`<div class="modal-top"><div><span class="eyebrow">BEGINNER KO‘RSATMA</span><h2>${escapeHTML(ex.name)}</h2></div><button class="close-modal" data-action="close-modal">×</button></div><p>${escapeHTML(ex.how)}</p><p class="subtle">${ex.sets} set × ${ex.reps}. Setlar orasida ${ex.rest||60} soniya dam oling. Harakat og‘riqli bo‘lsa, to‘xtating.</p><button class="primary-button full" data-action="close-modal">Tushunarli</button>`);break;}
 case 'month-prev':monthCursor=new Date(monthCursor.getFullYear(),monthCursor.getMonth()-1,1);renderCalendar();break;
 case 'month-next':monthCursor=new Date(monthCursor.getFullYear(),monthCursor.getMonth()+1,1);renderCalendar();break;
 case 'day-detail':dayDetail(btn.dataset.value);break;
 case 'close-modal':$('#modal').close();break;
 case 'save-profile':{$$('[data-profile]').forEach(el=>state.profile[el.dataset.profile]=el.value);upsertWeight(state.profile.currentWeight);await persist();route('settings');showToast('Profil yangilandi');break;}
 case 'add-weight':openModal(`<div class="modal-top"><div><span class="eyebrow">VAZN YOZUVI</span><h2>Bugungi vazn</h2></div><button class="close-modal" data-action="close-modal">×</button></div><label class="field-label">Vazn (kg)<input id="weight-entry" type="number" step="0.1" value="${state.profile.currentWeight||''}"></label><button class="primary-button full" data-action="save-weight">Saqlash ✓</button>`);break;
 case 'save-weight':{const weight=Number($('#weight-entry').value);if(weight>0){state.profile.currentWeight=weight;upsertWeight(weight);await persist();$('#modal').close();route('progress');}break;}
 case 'weekly-review':openModal(`<div class="modal-top"><div><span class="eyebrow">WEEKLY REVIEW</span><h2>Hafta yakuni 🌿</h2></div><button class="close-modal" data-action="close-modal">×</button></div><div class="detail-stats"><div><b>${weeklyWorkouts()} / 3</b><small>Mashqlar</small></div><div><b>${stepsAverage(7).toLocaleString()}</b><small>Qadam o‘rt.</small></div><div><b>${waterAverage(7).toFixed(1)} L</b><small>Suv o‘rt.</small></div></div><p>${weeklyReview()}</p><p class="subtle">Bir haftalik vazn tebranishi odatiy. Bir necha haftalik trendni kuzating.</p>`);break;
 case 'export':{const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`fitstart-backup-${key}.json`;a.click();URL.revokeObjectURL(a.href);showToast('JSON backup yuklandi');break;}
 case 'import':$('#import-file').click();break;
 case 'reset':openModal(`<div class="modal-top"><div><span class="eyebrow">DIQQAT</span><h2>Qaytadan boshlaysizmi?</h2></div><button class="close-modal" data-action="close-modal">×</button></div><p>Barcha qurilmadagi progress o‘chadi. Avval JSON backup oling.</p><div class="button-row"><button class="secondary-button" data-action="close-modal">Bekor qilish</button><button class="danger-button" data-action="confirm-reset">Hammasini o‘chirish</button></div>`);break;
 case 'confirm-reset':state=freshState();await persist();$('#modal').close();onboarding();break;
 }}

document.addEventListener('click',e=>{const routeLink=e.target.closest('[data-route]');if(routeLink){e.preventDefault();route(routeLink.dataset.route);return;}const btn=e.target.closest('[data-action]');if(btn)handleAction(btn);});
document.addEventListener('change',async e=>{if(e.target.id==='import-file'&&e.target.files[0]){try{const parsed=JSON.parse(await e.target.files[0].text());if(!parsed.profile||!parsed.checkins||!parsed.sessions)throw new Error('Invalid backup');state={...freshState(),...parsed};await persist();route(state.onboarded?'today':'today');showToast('Backup tiklandi');}catch{showToast('JSON faylini o‘qib bo‘lmadi');}e.target.value='';}});
document.addEventListener('input',e=>{if(e.target.matches('[data-weight]')){const session=state.sessions[todayKey()];const ex=session?.exercises.find(x=>x.id===e.target.dataset.weight);if(ex)ex.sets[Number(e.target.dataset.set)].weight=e.target.value;persist();}});
$('#profile-button').addEventListener('click',()=>route('settings'));
window.addEventListener('hashchange',()=>{const routeName=location.hash.slice(1);if(routeName&&routeName!==activeRoute)route(routeName);});

async function init(){
 $('#date-short').textContent=new Intl.DateTimeFormat('uz-UZ',{day:'numeric',month:'short'}).format(new Date());
 try{await Store.open();state=await Store.get()||freshState();}catch(e){console.warn('IndexedDB unavailable; using local fallback',e);state=JSON.parse(localStorage.getItem('fitstart-backup-state')||'null')||freshState();}
 if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register(new URL('sw.js',document.baseURI)).catch(console.warn);
 if(!state.onboarded){onboarding();return;}
 const wanted=location.hash.slice(1)||'today';route(['today','workout','calendar','progress','settings'].includes(wanted)?wanted:'today');
}
init();
