function renderToday(){
 const k=todayKey(),c=state.checkins[k]||{},t=trainingDay(k),s=state.sessions[k],steps=Number(c.steps||0),goal=Number(state.profile.stepsGoal||8000),mins=Number(s?.cardio||0);
 $('#main').innerHTML='<section class="simple-hero"><span class="eyebrow">'+fmtDate()+' · DAY '+t.day+'</span><div class="day-line"><div><h1>Salom 👋</h1><p>Bugun ham kichik qadam yetarli.</p></div><div class="streak-badge"><span>🔥</span><strong>'+calcStreak()+'</strong><small>kun</small></div></div><div class="today-task"><span>BUGUNGI VAZIFA</span><h2>'+(t.isTraining?'20 daqiqa piyoda yurish':'Yengil yurish yoki dam olish')+'</h2><p>'+(mins?mins+' daqiqa qayd qilindi ✓':'Qulay tezlikda yuring — bemalol gaplasha olishingiz kerak.')+'</p></div><button class="primary-button full" data-route="workout">'+(mins?'Rejani ko‘rish':'Yurishni boshlash')+' →</button></section><section class="panel simple-goal"><div class="panel-title"><div><span class="eyebrow">QADAMLAR</span><h3>'+steps.toLocaleString()+' / '+goal.toLocaleString()+'</h3></div>'+ring(steps,goal,'var(--mint)',76)+'</div><button class="secondary-button" data-action="edit-steps">Qadam sonini yozish</button></section><section class="panel simple-goal"><span class="eyebrow">SUV</span><h3>'+Number(c.water||0).toFixed(1)+' / '+Number(state.profile.waterGoal||2.5).toFixed(1)+' litr 💧</h3><button class="secondary-button" data-action="add-water">+ Bir stakan (250 ml)</button></section><section class="panel"><span class="eyebrow">BUGUNGI VAZN</span><div class="checkin-row"><label class="mini-input">kg <input data-checkin="weight" value="'+escapeHTML(c.weight??state.profile.currentWeight)+'" inputmode="decimal" placeholder="masalan 92.4"></label><button class="save-mini" data-action="save-checkin">Saqlash</button></div><p class="subtle">Kunlik o‘zgarish odatiy. Bir necha haftalik yo‘nalishga qarang.</p></section><section class="panel">Yugurish shart emas. Avval muntazam yurish odatini yarating.</section>';
}
function renderWorkout(){
 const t=trainingDay(),s=state.sessions[todayKey()],w=Math.min(4,t.week),walking=w<=2,m=Number(s?.cardio||0);
 $('#main').innerHTML='<header class="simple-heading"><span class="eyebrow">SODDA REJA · 4 HAFTA</span><h1>Yurish bilan boshlang</h1><p>Yugurish majburiy emas. Avval yurishga odatlaning.</p></header><section class="panel plan-card"><span class="eyebrow">HOZIR · '+(walking?'1–2':'3–4')+'-HAFTA</span><h2>'+(walking?'15–20 daqiqa qulay yurish':'Yurish va ixtiyoriy yengil yugurish')+'</h2><p>Haftasiga 3 kun, kun oralatib. Oradagi kunlari dam oling yoki yengil sayr qiling.</p><div class="plan-steps"><div><b>1</b><span><strong>5 daqiqa</strong> sekin yurib isinib oling.</span></div><div><b>2</b><span><strong>'+(walking?'15–20 daqiqa qulay yurish':'1 daqiqa yengil yugurish + 90 soniya yurish × 7')+'</strong></span></div><div><b>3</b><span><strong>5 daqiqa</strong> sekin yurib yakunlang.</span></div></div><p class="subtle">Gaplasha oladigan tezlikda yuring. Nafas qisilib, gapirish qiyinlashsa sekinlashing.</p></section><section class="panel plan-card"><span class="eyebrow">QANDAY YURAMAN?</span><ol><li>Qulay oyoq kiyim va tekis, xavfsiz yo‘l tanlang.</li><li>Avval sekin, keyin odatdagi tezlikda yuring.</li><li>Yelkani bo‘sh tuting, tabiiy qadam tashlang, nafasni ushlamang.</li><li>Bemalol gaplasha olish tezligi to‘g‘ri.</li></ol></section><section class="panel plan-card"><span class="eyebrow">KEYINROQ</span><h3>3–4-hafta, tayyor bo‘lsangiz</h3><p>1 daqiqa yengil yuguring, 90 soniya yuring; 7 marta takrorlang. Shart emas — yurishning o‘zi ham yaxshi mashq.</p></section><section class="panel plan-card"><span class="eyebrow">BUGUNGI HARAKAT</span><label class="simple-field">Faoliyat<select id="activity-type"><option>Walking</option><option>Treadmill</option><option>Running intervals</option><option>Cycling</option><option>Elliptical</option></select></label><label class="simple-field">Daqiqa<input id="activity-minutes" type="number" min="1" value="'+(m||20)+'"></label><button class="primary-button full" data-action="save-activity">Harakatni saqlash</button><p class="subtle">'+(m?'Bugun saqlandi: '+m+' daqiqa':'Bajargan daqiqangizni kiriting.')+'</p></section><div class="safety-note"><span>ⓘ</span><p>O‘tkir og‘riq, bosh aylanishi yoki ko‘krak og‘rig‘i bo‘lsa to‘xtang. Bu tibbiy maslahat emas.</p></div>';
}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action="save-activity"]');if(!b)return;const mins=Number($('#activity-minutes').value),kind=$('#activity-type').value;if(mins<1){showToast('Daqiqani kiriting');return;}const k=todayKey();state.sessions[k]??={date:k,letter:trainingDay().letter,exercises:[],cardio:0,completed:false};state.sessions[k].cardio=mins;state.sessions[k].cardioType=kind;state.sessions[k].completed=true;state.sessions[k].finishedAt=new Date().toISOString();await persist();route('today');showToast(mins+' daqiqa saqlandi ✓');});
function onboarding(){
 $('#main').innerHTML='<div class="onboarding"><div class="brand large"><span class="brand-mark">F</span><span>fit<span class="brand-accent">start</span></span></div><span class="eyebrow">OZ-OZDAN, MUNTazam</span><h1>Yurishdan boshlaymiz.</h1><p class="muted">Oddiy reja. Ma’lumotlaringiz shu telefonda saqlanadi.</p><form id="onboarding-form" class="form-stack"><label>Hozirgi vazn (kg) — ixtiyoriy<input name="currentWeight" type="number" step="0.1" placeholder="masalan 92.4"></label><label>Maqsad vazn (kg) — ixtiyoriy<input name="targetWeight" type="number" step="0.1" placeholder="masalan 80"></label><button class="primary-button full">Rejani boshlash →</button></form></div>';
 $('#onboarding-form').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),w=f.get('currentWeight');state.profile={...state.profile,goal:'lose',currentWeight:w,startWeight:w,targetWeight:f.get('targetWeight'),experience:'never',days:3,stepsGoal:8000,startDate:todayKey()};upsertWeight(w);state.onboarded=true;await persist();route('today');});
}
