const assert = require('node:assert/strict');
const fs = require('node:fs');
const { execFileSync } = require('node:child_process');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
for (const file of ['app.js', 'sw.js']) execFileSync(process.execPath, ['--check', path.join(root,file)]);
const html = fs.readFileSync(path.join(root,'index.html'),'utf8');
const app = fs.readFileSync(path.join(root,'app.js'),'utf8');
const sw = fs.readFileSync(path.join(root,'sw.js'),'utf8');
const manifest = JSON.parse(fs.readFileSync(path.join(root,'manifest.webmanifest'),'utf8'));
assert.match(html, /name="viewport"/);
assert.match(html, /apple-mobile-web-app-capable" content="yes"/);
assert.equal(manifest.display, 'standalone');
assert.ok(app.includes("indexedDB.open(DB_NAME"), 'device database must use IndexedDB');
assert.ok(app.includes('navigator.storage?.persist?.()'), 'app should request persistent storage where supported');
assert.ok(app.includes('function ensureSession'), 'workout state should be saved by day');
assert.ok(app.includes('function weightChart'), 'weight chart must exist');
assert.ok(app.includes("case 'export'"), 'JSON export action must exist');
assert.ok(app.includes("case 'import'"), 'JSON import action must exist');
assert.ok(app.includes("case 'adjust-nutrition'"), 'nutrition quick buttons must work');
assert.ok(sw.includes("'./app.js'"), 'offline cache must include application code');
for (const file of ['icons/icon-192.png','icons/icon-512.png']) assert.ok(fs.existsSync(path.join(root,file)), `missing ${file}`);
console.log('FitStart smoke checks passed.');
